/** list of JS objects that are required for the worker to run */
export const minSafeObjects = [
  'self',
  'postMessage',
  '__proto__',
  '__defineGetter__',
  '__defineSetter__',
  '__lookupGetter__',
  '__lookupSetter__',
  'Date',
  'Object',
  'addEventListener',
  'encodeURIComponent',
  'dispatchEvent',
  'globalThis',
] as const satisfies ReadonlyArray<string>

/** default list of JS objects the untrusted code can have access to */
export const defaultSafeObjects = [
  ...minSafeObjects,
  'constructor',
  'hasOwnProperty',
  'isPrototypeOf',
  'propertyIsEnumerable',
  'eval',
  'Array',
  'Boolean',
  'Function',
  'toLocaleString',
  'toString',
  'String',
  'undefined',
  'Infinity',
  'isFinite',
  'isNaN',
  'Math',
  'NaN',
  'Number',
  'parseFloat',
  'parseInt',
  'RegExp',
  'URL',
  'Blob',
  'Error',
  'TypeError',
  'Symbol',
  'Uint8Array',
  'Buffer',
  'ArrayBuffer',
  'clearTimeout',
  'setTimeout',
  'valueOf',
  'DataView',
  'Map',
  'WeakMap',
  'Set',
  'Promise',
  'console',
  'JSON',
] as const satisfies ReadonlyArray<string>
